require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'
require_relative '../node_modules/react-native/scripts/react_native_pods'

platform :ios, '13.0'

target 'RealmRNSandbox' do
  $RNFirebaseAnalyticsWithoutAdIdSupport=true
  permissions_path = '../node_modules/react-native-permissions/ios'
  config = use_native_modules!
  use_react_native!(:path => config["reactNativePath"])
end

post_install do |installer|
  installer.pods_project.build_configurations.each do |config|
    config.build_settings["ONLY_ACTIVE_ARCH"] = "YES"
    config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64"
  end
end